### PR TITLE
Add Theme Mode Switch Option (Refactor)

### PR DESCRIPTION
**Pull request by ohitsdylan**
Now with a CSS-based Implementation™️ for Dark Mode

### CODE REVIEW

**Comment by apankrat** [comment]
Sorry about the delay, got a bit busier than I'd like to be.
I will do the review tomorrow or the day after.

**Comment by apankrat** [comment]
Never mind, did it now :) The magic incantation you are looking for is `toggleClass` (and don't forget to `return false` to prevent # from being appended to the URL) -

```
$('.theme-swap').click(function() {
        $('body').toggleClass('dark');
        return false;
});
```

**Comment by ohitsdylan** [comment]
thanks for that @apankrat ! a little new to the JS thing, so assistance is appreciated.

**Comment by apankrat** [comment]
Thanks for the patch. I merged it in and then ended up making several changes. I made theme choice persistent across re-launches. I replaced red on-hover in the board menu with orange (b/c red is reserved for destructive actions) and darkened the whole thing a bit. Also, you missed the case of items being dragged around, I patched that. Tidied up the CSS and JS a bit too, mostly for consistency with existing code. The end result looks like this now -

screenshot

**Comment by ohitsdylan** [comment]
Wonderful! Thanks for this.

**Pull request merged**
