### PR TITLE
Deploy in docker container

### PR DESCRIPTION
**Pull request by rsoper**
Using Nginx, create a docker image containing this application and run in docker. Docker compose file included for quick local build and deploy. 

Not sure if there was any interest in this, but I will be running it this way personally. Love the tool and will be working on a way to make data persist so I can use it more extensively.

### CODE REVIEW

**Comment by rsoper** [comment]
Tested and working on amd64 and ARMv7 architectures

**Comment by apankrat** [comment]
Hi Richard,

Thanks for the submission.

I don't think this is something that should be in the main repo. In particular, I don't see myself using this and as such I have no interest in giving this the first-class endorsement, because it would automatically put an onus of supporting it on me. However I have no problem adding a link to "dockerizing" instructions into the readme if these are hosted in another repo and looked after by someone else.

Alex

**Comment by rsoper** [comment]
Thought that might be the case but figured Id give it a go. In that case Ill be maintaining the docker support on my main branch rsoper/nullboard. 

Thanks!

**Comment by apankrat** [comment]
OK, I dropped a [link](https://github.com/apankrat/nullboard/blob/master/README.md#dockerized-version) to your repo into the Readme.

**Pull request closed without merging**
