### PR TITLE
Allows the user to assign colors to notes.

### PR DESCRIPTION
**Pull request by dan3721**
Needs a tweak to work in harmony with the dark theme.

### CODE REVIEW

**Comment by apankrat** [comment]
Apologies for the delay. I'll take a look at this today-tomorrow.

**Comment by apankrat** [comment]
OK, nice and clean. I will tweak a couple of things and merge it in.

**Comment by apankrat** [comment]
This needs some rework.

1. JS has no business of messing with items' CSS properties. JS should be adding/removing classes.

2. Saving raw color values in the db is also not a good idea. What needs to be saved is a "color tag id" ("color class"), which is mapped by CSS onto a specific color. Because that's what this feature is ultimately about - grouping notes. Whether this translates into rendering them with a pale red background is secondary.

So the rework is to make color tag selector merely set/clear "color" classes on the notes. These classes need to be mapped onto certain styling with CSS. And it's them that will be saved in the db.

There are some smaller cosmetic changes as well I'll make.

3. The whole thing should be a global option, so it should be possible to hide "C" from the note's menu at a board-level.

4. Color selector should be, IMO, horizontal - basically a list of squares. Still perfectly usable, but it keeps the whole thing in confines on a note.

5. Potentially, there can be a support for switching to a different palette or using a different style, e.g. coloring the left edge of a note instead of its background.

I'll try and do this over the weekend.

**Comment by timdonovanuk** [comment]
Could this be merged? Nullboard is amazing but for me missing this one simple feature (in lieu of labels).

**Comment by timdonovanuk** [comment]
Could this be merged please? :older_man:

**Comment by NickRaleigh** [comment]
This is a great feature, but doesn't seem to work with the dark theme.

**Pull request merged**
